"""first release

Revision ID: c5382eb14492
Revises:
Create Date: 2024-12-07 19:04:32.009228

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5382eb14492"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "employee",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("email", sa.String(length=40), nullable=False),
        sa.Column("password", sa.String(length=40), nullable=False),
        sa.Column("phone_number", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_table(
        "order",
        sa.Column("table", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "WAITING", "IN_PRODUCTION", "FINALIZED", name="statusenum"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("description", sa.String(length=40), nullable=False),
        sa.Column("image", sa.String(length=40), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    op.drop_table("order")
    op.drop_table("employee")
    op.drop_table("category")
    # ### end Alembic commands ###
